<?php

	# newsletter stuff
	$name = $_GET['name'];
	$to      = $_GET['email'];
	$subject = 'Newsletter: 10 Steps to Loving Your Body';
	$message = '<h1>10 Steps to Loving Your Body</h1>
	<ol>
		<li>First, and most importantly, <strong>look at what\'s underneath the negativity</strong>. I\'m not talking about your body here, I\'m talking about your feelings. Are you overwhelmed? Feeling unappreciated? Traumatized? Lost? Our bodies often become a scapegoat for other dissatisfactions and hurts. This is how you can have a "good body day" back to back with a "bad body day" when there\'s clearly no legitimate, measurable change in body composition day to day. Maybe this sparks a list of all the things you don\'t like about life right now or maybe you can\'t identify anything. I assure you, if you can\'t think of ANYTHING that isn\'t working for you in life besides your body, you\'re disconnected from your feelings. I\'ve been a therapist (and a person) way too long to buy that your body is the problem. Whether you know what\'s hard in life right now or not, start writing your list now. If you don\'t know what to list write your version of "1. I don\'t know what to write. 2. This is stupid. 3. This has nothing to do with my body." Keep listing until something not body related pops up. Seriously, do this now before starting the next step.<br/><br/></li>
		<li><strong>Have compassion</strong> for having to deal with what\'s on your list. Sometimes our lists are long and heart-wrenching. Sometimes they are a manageable list of minor complaints. We are more likely to have body hatred when it is the former. If you are reading these 10 steps I am guessing you have some hard stuff you\'re dealing with (or not dealing with, but hard stuff nonetheless). Validate that deep down, you feel like crap and it\'s getting projected on to your thighs or your belly or the dimples in your butt. You don\'t have to fix or change this right this second. Just be a little curious about how that happened.<br/><br/></li>
		<li><strong>Take a look at the spoken and unspoken messages</strong> you have received and given about bodies. The media is easy to pick on. They basically walk around with a dunce cap on all the time asking to be blamed. But what about your family? Was your mom constantly talking about how fat she was or did she have an air of confidence no matter her body shape? Did your divorced dad only date painfully thin women or was there body diversity amongst the women he was attracted to? Did you ever tell your best friend not to worry about her weight, that she could diet &amp; exercise it off or did you tell her she\'s beautiful &amp; wish she could love herself as she is right now? Have you told yourself you\'ll be more lovable when you\'re smaller/more toned or do you fully accept that you are lovable this exact moment. These are the messages that spin us into misery or confidence. The way you think about yourself determines how you feel about yourself. You can\'t spew shaming messages and expect yourself to somehow be confident.<br/><br/></li>
		<li>I mentioned the media. <strong>Are you consuming media that make it harder to love yourself</strong>? Do you look at gossip or fashion magazines? Do you click on the links for the best &amp; worst celebrity beach bodies? Is watching weight loss shows, shows where appearance is discussed for more than a few seconds, shows that only employ actors who fit within a rigid beauty ideal a part of your life? Do the movies you watch have people of differing shapes, sizes, ethnicities, gender expressions &amp; abilities? Do you listen to music that describes the non-physical attributes of women? Try consuming media that doesn\'t conform to the unattainable attractiveness standards.<br/><br/></li>
		<li><strong>Wear clothes that fit, feel comfortable &amp; look good</strong>. Please, please, please don\'t squeeze into a size that doesn\'t really fit because it\'s a more "desirable" size. Everyone feels fat when their pants seams are about to burst. If your waistband cuts into your stomach so hard you\'re constantly aware of the bulge above it, you\'re going to feel fat. This doesn\'t mean you have to live in yoga pants and too-big t-shirts. You will feel more confident if you are wearing clothes you like in the size that fits, even if you hate the size, than you will in a size that doesn\'t fit. You may hate the right size &amp; fear you\'ll be aware of it, but it\'s not going to whisper "this is a size __" throughout the day as often as your too tight clothes will scream "you\'re fat" every time you bend your knee, sit down, sigh, pull them down and generally move.<br/><br/></li>
		<li><strong>Stop assuming that thin people are happier &amp; more successful than you</strong>. Perhaps there are things that are easier for them in life. Perhaps some thin people are happy and successful. You are not unhappy or less successful because you aren\'t as thin. Yes, there is size discrimination. First, vet whether or not you actually qualify for the category that gets discriminated about. Be real. If you\'re a size 6 when you want to be a size 2, this does not count for you. If you are a person of size and have been discriminated against I want to validate that all discrimination is unacceptable and disgusting. That doesn\'t mean all thin people are happy. It doesn\'t mean they all succeed. I have rail thin women in my office who hate themselves to the depth of their being. I have skinny men in my office who are too depressed to apply for a job, much less get one. Your path to happiness and success is not paved in lost pounds. Your life doesn\'t start when you hit a particular weight. Your life is right now.<br/><br/></li>
		<li><strong>Get okay with the word "fat"</strong>. Yes, that other F-word. The F-word that is almost less acceptable to say! The Fat Acceptance Movement is doing a great job reclaiming the word fat. In the way the LGBTQ community reappropriated "queer" and intellectuals proudly call themselves "nerds" and environmental activists wear wear "tree-hugger" buttons and folks who live in the country might call themselves "rednecks," taking back the formerly pejorative "fat" takes some of the sting out of it. Here\'s the deal: you have fat on your body. I have fat on my body. I\'m not a medical expert, but I\'m pretty sure the only people with no fat on their bodies had it eaten off by insects (as in dead, not some new fat-sucking product). We eat foods with fat grams in them which make them taste better and keep us satisfied longer. Fat is not a bad thing. It\'s an inevitability. It\'s been used as an insult for so long that it makes people shudder to hear it. When you saw it in bold above, did you not cringe a little? Fat doesn\'t have to be an insult, it can be a descriptor. People will not be comfortable. That\'s ok. You don\'t have to make them comfortable. I told a sales associate at a store that I preferred a thicker fabric because I have cellulite &amp; don\'t like to highlight it. She looked at me with a combination of pity &amp; discomfort. I wasn\'t insulting myself or being self-deprecating- I was simply stating a fact that I\'m usually pretty neutral about (for the exceptions, see #1). Someday, when "fat" is a more neutral descriptor, she may remember the times she got squirmy when people referred to it.<br/><br/></li>
		<li><strong>Find a body image role model</strong>. This is hard. It feels like there aren\'t a lot out there. If you don\'t personally know someone, pick an activist (really anyone who accepts their body as is &amp; talks about it is an activist in my book). Search "fat acceptance" and see what you come up with. Even if you are a smaller person, the fat acceptance movement is for you. The less rigid we all are about beauty ideals, the better. If you know someone who accepts him/herself, ask how they got there. Maybe they got through adolescence unscathed &amp; it never occurred to them to be self-critical, but that\'s pretty rare. You\'re more likely to hear the story of how someone fought for self-love &amp; didn\'t give up, found a higher priority or were inspired by someone else. Sometimes it\'s great to see an example of how to disengage with the negative self-talk &amp; what freedom it brings. Conversely, notice what happens when you\'re around your friends who struggle with body image.<br/><br/></li>
		<li><strong>Stop Fat Talk</strong>. Make a rule. Calling yourself fat (i.e. using it as an insult) never made you skinny. Fat talk is actually far more likely to increase your weight. If it\'s a safe environment to do so, ask the people you live with to make it a Fat Talk Free Zone. If someone starts complaining about his/her body, ask how they\'re feeling about the rest of life. S/he will probably feel better after a conversation about the boss from hell or the class that will tank his/her GPA than the usual "You\'re SO not fat" with an offer to go to the gym together more.<br/><br/></li>
		<li>For the love of all that is good in the world, <strong>stop dieting</strong>. I know it feels like such an accomplishment to get through a day being "good" and that seeing your weight go down makes you feel like you can take on the world. But you know it won\'t last. It\'s not because you are weak-willed or lazy; it\'s because no diet is sustainable. You aren\'t necessarily "stuck" at your current weight, either. There is an alternative where you are healthy, all foods are "legal" and you don\'t need obsession, a calorie counter or a meal plan to feel good in your body.<br/><br/></li>
		<li>Does this sound like the life you want to live? I\'d love to help you get there. Give me a call at 828-333-3654 or email me at <a href="mailto:allisonpuryear@icloud.com">allisonpuryear@icloud.com</a> if you\'d like more personalized help.</li>
	</ol>
	<p>For the love of all that is good in the world, stop dieting. I know it feels like such an accomplishment to get through a day being "good" and seeing your weight go down makes you feel like you can take on the world. Did you know the best predictor for weight gain in 2 years is whether or not you\'re on a diet now? Did you know that each time you diet, your set point weight, the weight at which your body is most comfortable &amp; operates the best, creeps higher? If you\'re on a diet right now, you\'re going to "fall off the wagon." It\'s not because you are weak-willed or lazy, it\'s because no diet is sustainable. Do you know anyone at all who was on the same diet continuously for years without an eating disorder? Do you know anyone who lost weight, stopped a diet &amp; maintained that weight? It is biologically impossible. You aren\'t necessarily "stuck" at your current weight, either. Learning to listen to your hunger &amp; satiety cues &amp; checking in to see what your body (not your head) wants to eat is the path to your healthiest self. Spoiler alert- sometimes your body wants salad &amp; sometimes it wants snack cakes. All foods are "legal" and you don\'t need your head, a calorie counter or a meal plan to get where you feel good in your body.</p>';
	$headers = 'From: allisonpuryear@icloud.com' ."\r\n";
	$headers .= 'Reply-To: allisonpuryear@icloud.com' . "\r\n";
	$headers .= "MIME-Version: 1.0\r\n";
	$headers .= "Content-Type: text/html; charset=ISO-8859-1\r\n";

	mail($to, $subject, $message, $headers);

	// # write to a file
	$file = "list.txt";
	$fh = fopen($file, 'a') or die("can't open file");
	$stringData = "Name: " . $name . "\nEmail: " . $to . "\n\n";
	fwrite($fh, $stringData);
	fclose($fh);

?>
